apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/

patchesJson6902:
  - target:
      group: serving.knative.dev
      version: v1
      kind: Service
      name: nginx-app
    path: static_patches.yaml
  # - target:
  #     group: serving.knative.dev
  #     version: v1
  #     kind: Service
  #     name: doc-puller
  #   path: rendered_patch.yaml
