repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: fix-encoding-pragma
      - id: name-tests-test
      - id: check-docstring-first
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types_or: [python]
