apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nginx-app
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    # run.googleapis.com/ingress: internal
    # run.googleapis.com/ingress-status: internal
    run.googleapis.com/launch-stage: BETA
spec:
  traffic: []
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/maxScale: "4"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 3600
      containers:
        - image: us-docker.pkg.dev/bf-infra-tooling-xyz/demo/nginx-app:latest
          ports:
            - name: http1
              containerPort: 80
          resources:
            limits:
              cpu: 1
              memory: 256M
